// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBz_dOxKgGkz84VTnmAWXP556dMqJWGLo',
    appId: '1:129047565304:web:ae1de5d42e886fe450bc0d',
    messagingSenderId: '129047565304',
    projectId: 'hydrodeck-e6fea',
    authDomain: 'hydrodeck-e6fea.firebaseapp.com',
    storageBucket: 'hydrodeck-e6fea.firebasestorage.app',
    measurementId: 'G-2L9GS59H3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvqqaAZZUYp5OWYtILJlBm7OnxxstN2OQ',
    appId: '1:129047565304:android:815e77ceb2af273450bc0d',
    messagingSenderId: '129047565304',
    projectId: 'hydrodeck-e6fea',
    storageBucket: 'hydrodeck-e6fea.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBz_dOxKgGkz84VTnmAWXP556dMqJWGLo',
    appId: '1:129047565304:web:f978068d97a6df7450bc0d',
    messagingSenderId: '129047565304',
    projectId: 'hydrodeck-e6fea',
    authDomain: 'hydrodeck-e6fea.firebaseapp.com',
    storageBucket: 'hydrodeck-e6fea.firebasestorage.app',
    measurementId: 'G-N1TR0GV6NK',
  );
}
